# Generated by Django 4.2.2 on 2023-07-19 14:49

import delivery_company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_company', '0002_medication_order_loaditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.IntegerField(validators=[delivery_company.validators.validate_weight_limit]),
        ),
    ]
