# Generated by Django 4.2.2 on 2023-07-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_company', '0003_alter_drone_weight_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_company.drone')),
            ],
        ),
    ]
